Program Ejemplo0
!Aqui haremos un Indice
!por lo que este no es un Ejemplo de Aprendizaje

Print *, 'Ejemplo1  : Definiciones de Variables y Constantes'
Print *, 'Ejemplo2  : Usos del Comando Print y Read'
Print *, 'Ejemplo3  : Una demostración de la No Asociatividad en Calculos Numéricos'
Print *, 'Ejemplo4  : Uso de una Funcion, definida en el mismo archivo'
Print *, 'Ejemplo5  : Uso de una Funcion, definida en un archivo externo'
Print *, 'Ejemplo6  : Uso de una Subroutina, definido Interno'
Print *, 'Ejemplo7  : Uso de una Subroutina, definido Externo'
Print *, 'Ejemplo8  : Uso de variables tipo In, Out, InOut en funciones y Subroutinas'
Print *, 'Ejemplo9  : Uso de un Modulo, definido Interno y nros complejos'
Print *, 'Ejemplo10 : Uso del If Else If y operadores logicos'
Print *, 'Ejemplo11 : Uso de Select case '
Print *, 'Ejemplo12 : Uso de variables y operadores logicos'
Print *, 'Ejemplo13 : Uso de del Ciclo DO, END DO y EXIT'
Print *, 'Ejemplo14 : Uso del Do While End Do'
Print *, 'Ejemplo15 : Uso de Do Cycle'
Print *, 'Ejemplo16 : Uso de COMMON'
Print *, 'Ejemplo17 : Uso de vectores y matrices'
Print *, 'Ejemplo18 : Uso de Format'
Print *, 'Ejemplo19 : Uso de Lectura y Escritura de Archivo'
Print *, 'Ejemplo20 : Uso de una Rutina generadora de nros random'
Print *, 'Ejemplo21 : Uso de contador de eventos por eventos y de tiempo'
Print *, 'Ejemplo22 : Ejemplo de Monte Carlo para calcular el valor de Pi'
Print *, 'Ejemplo23 : Ejemplo de Integracion por Monte Carlo'
Print *, 'Ejemplo24 : Ejemplo de Caminata Aleatoria en dos dimensiones'
Print *, 'Ejemplo25 : Ejemplo de una distribucion de gaussiana de nros aleatorios'
Print *, 'Ejemplo26 : Ejemplo de una distribucion uniforme en un disco'
Print *, 'Ejemplo27 : Ejemplo de aplicacion el método del rechazo'
Print *, 'Ejemplo28 : Ejemplo I aplica el método del rechazo mixto con Metodo Inverso'
Print *, 'Ejemplo29 : Ejemplo II aplica el método del rechazo mixto con Metodo Inverso'
Print *, 'Ejemplo30 : Ejemplo para la Creación de Archivos Gráficos PPM'
Print *, 'Ejemplo31 : Ejemplo de crecimiento de un cristal bidimensional'
Print *, 'Ejemplo32 : Ejemplo para transformar nros en Char y usarlos como tail en Filename'
Print *, 'Ejemplo33 : Ejemplo de crecimiento de un cristal tridimensional'
Print *, 'Ejemplo34 : Ejemplo de la Transición Termodonámica en un Modelo de Ising'

End Program Ejemplo0												
